version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - app_network

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
