version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
