version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://0.0.0.0:8080

networks:
  app_network:
    driver: bridge
